server:
  port: 80
cors:
  originPatterns: http://0.0.0.0:8080,https://erudio.com.br,http://0.0.0.0:3000
file:
  upload-dir: /Users/marco.pegado/Documents/code/uploadDir
security:
  jwt:
    token:
      secret-key: 53cr37
      expire-length: 3600000
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://0.0.0.0:3306/rest_with_spring_boot_erudio?useTimezone=true&serverTimezone=UTC
    username: root
    password: senha
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: none
   # properties:
    #  hibernate:
     #   dialect: org.hibernate.dialect.MySQLDialect
    show-sql: false
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2KB
      max-file-size: 200MB
      max-request-size: 215MB
springdoc:
  pathsToMatch: 
    - /auth/**
    - /api/**/v1/**
  swagger-ui:
    use-root-path: true
    